version: '3.7'

services:
  bot:
    container_name: ${project}
    restart: always
    depends_on:
      - traefik
    build:
      context: .
      dockerfile: ./bot/Dockerfile.dev
    networks:
      - traefik_network
    ports:
      - "${listen_port}:${listen_port}"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      # Network
      - "traefik.docker.network=traefik_network"

      # Service
      - "traefik.http.services.${project}-service.loadbalancer.server.port=${listen_port}"

      # Router
      - "traefik.http.routers.${project}-router.rule=Host(`${base_url}`) && PathPrefix(`${bot_path}`)"
      - "traefik.http.routers.${project}-router.service=${project}-service"

      # Entry point
      - "traefik.http.routers.${project}-router.entrypoints=web"

networks:
  traefik_network:
    driver: overlay
    external: true