FROM python:3.11

WORKDIR /home

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt && \
    pip install envparse

RUN apt-get update && apt-get install -y tcpdump

COPY . .

EXPOSE 80

CMD [ "python", "./bot/bot.py" ]