FROM python:3.11

WORKDIR /

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN python -m venv venv
RUN /bin/bash -c "source ./venv/bin/activate"

COPY . .

CMD [ "python", "./bot/bot.py" ]